name: Deploy ke VPS

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Pull dari repository ini
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            cd /home/kelompok4/AplikasiAnggaran
            git pull origin master

      - name: Remove semua container dan images yang sudah ada
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker system prune -a -f

      - name: Build image baru dan container baru
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            cd /home/kelompok4/AplikasiAnggaran
            docker build -t anggaran .
            docker run -d -it -p 8085:80 anggaran
